import Config

# Configure your database
# config :generator, Generator.Repo,
#   username: "remotepostgres",
#   password: "remotepostgres",
#   hostname: "192.168.1.54",
#   database: "generator_dev",
#   stacktrace: true,
#   show_sensitive_data_on_connection_error: true,
#   pool_size: 10

config :generator, Generator.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "generator_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# config/config.exs
config :generator, Oban,
  engine: Oban.Engines.Basic,
  queues: [default: 10],
  repo: Generator.Repo

config :generator, Oban,
  queues: [default: System.schedulers_online()],
  repo: Generator.Repo,
  plugins: [
    {Oban.Plugins.Lifeline, rescue_after: :timer.minutes(60)}
  ]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :generator, GeneratorWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "EI/s23SDwd9ASvQnUnyWQcbToNe9429iRxj+F1oQyUmX44gPHO77qsj1AmQHBv+c",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :generator, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
